#!/usr/bin/env python3
"""
evaluate_url.py — Measure accuracy of Scan 1 (Static URL Heuristics).

Loads analysis.csv (already generated by url.py) and the labelled source
datasets, merges them, then reports ROC-AUC, best-threshold F1, a full
classification report, and a confusion matrix.

Usage:
    python evaluate_url.py
    python evaluate_url.py --analysis analysis.csv --dataset "Phishing Email Dataset"
"""

import argparse
import csv
import glob
import os
import sys

# Raise CSV field limit — some email bodies exceed the default 128 KB
try:
    csv.field_size_limit(10_000_000)
except OverflowError:
    csv.field_size_limit(2**31 - 1)

import numpy as np
import pandas as pd
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    roc_auc_score,
)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis", default="analysis.csv")
    parser.add_argument("--dataset",  default="Phishing Email Dataset")
    args = parser.parse_args()

    # ── 1. Load analysis.csv ────────────────────────────────────────────────
    print(f"Loading analysis : {args.analysis}")
    analysis = pd.read_csv(args.analysis)
    analysis["max_risk_score"] = pd.to_numeric(
        analysis["max_risk_score"], errors="coerce"
    ).fillna(0)
    analysis["source_file"] = analysis["source_file"].apply(os.path.basename)
    analysis["row_index"] = (
        pd.to_numeric(analysis["row_index"], errors="coerce").fillna(-1).astype(int)
    )
    print(f"  {len(analysis):,} rows\n")

    # ── 2. Load ground-truth labels ─────────────────────────────────────────
    print(f"Loading labels   : {args.dataset}/")
    records = []
    for fpath in glob.glob(os.path.join(args.dataset, "*.csv")):
        with open(fpath, encoding="utf-8", errors="ignore") as f:
            for i, row in enumerate(csv.DictReader(f)):
                lbl = row.get("label", "").strip()
                if lbl in ("0", "1"):
                    records.append({
                        "source_file": os.path.basename(fpath),
                        "row_index":   i,
                        "label":       int(lbl),
                    })

    if not records:
        print("ERROR: No labelled rows found. Check dataset path and label column.")
        return

    labels = pd.DataFrame(records)
    print(f"  {len(labels):,} labelled rows  "
          f"(phishing={labels['label'].sum():,}, "
          f"legit={(labels['label']==0).sum():,})\n")

    # ── 3. Merge ─────────────────────────────────────────────────────────────
    merged = analysis.merge(labels, on=["source_file", "row_index"], how="inner")
    print(f"Merged rows : {len(merged):,}")
    print(f"  Phishing  : {(merged['label'] == 1).sum():,}")
    print(f"  Legit     : {(merged['label'] == 0).sum():,}\n")

    if merged.empty:
        print("ERROR: Merge produced 0 rows — check source_file / row_index alignment.")
        return

    scores = merged["max_risk_score"].values
    truths = merged["label"].values

    # ── 4. ROC-AUC ───────────────────────────────────────────────────────────
    auc = roc_auc_score(truths, scores)
    print("=" * 55)
    print(f"  ROC-AUC Score          : {auc:.4f}")
    print("=" * 55)

    # ── 5. Find best F1 threshold automatically ──────────────────────────────
    best_f1, best_t = 0.0, 0
    for t in range(0, 101, 5):
        preds = (scores > t).astype(int)
        f1 = f1_score(truths, preds, zero_division=0)
        if f1 > best_f1:
            best_f1, best_t = f1, t

    print(f"\n  Best threshold         : score > {best_t}")
    print(f"  F1 at best threshold   : {best_f1:.4f}\n")

    # ── 6. Full classification report ────────────────────────────────────────
    preds = (scores > best_t).astype(int)
    print("Classification Report:")
    print(classification_report(truths, preds, target_names=["Legit", "Phishing"]))

    # ── 7. Confusion matrix ──────────────────────────────────────────────────
    cm = confusion_matrix(truths, preds)
    tn, fp, fn, tp = cm.ravel()
    print("Confusion Matrix:")
    print(f"  True Negatives  (Legit correctly cleared) : {tn:,}")
    print(f"  False Positives (Legit wrongly flagged)   : {fp:,}")
    print(f"  False Negatives (Phishing missed)         : {fn:,}")
    print(f"  True Positives  (Phishing correctly caught): {tp:,}")

    # ── 8. Per-threshold F1 table ────────────────────────────────────────────
    print("\nF1 score across thresholds:")
    print(f"  {'Threshold':>10}  {'F1':>6}  {'Precision':>10}  {'Recall':>8}")
    for t in range(0, 101, 10):
        p = (scores > t).astype(int)
        from sklearn.metrics import precision_score, recall_score
        f1  = f1_score(truths, p, zero_division=0)
        pre = precision_score(truths, p, zero_division=0)
        rec = recall_score(truths, p, zero_division=0)
        marker = "  ← best" if t == best_t else ""
        print(f"  {t:>10}  {f1:>6.3f}  {pre:>10.3f}  {rec:>8.3f}{marker}")


if __name__ == "__main__":
    main()
